print to stderr typo

diff --git a/Aliases/ipfrec b/Aliases/ipfrec
--- a/Aliases/ipfrec
+++ b/Aliases/ipfrec
@@ -30,7 +30,7 @@ ipfrec() {
 		done < <(echo "$OBJECT_LIST")
 	}
 	if [[ $(ipfs 2>/dev/null) == "" ]] ; then
-		echo "Error: IPFS is either not installed or not in your \$PATH" 2>&1
+		echo "Error: IPFS is either not installed or not in your \$PATH" >&2
 		return 1
 	fi
 	FILESONLY=false
